keys:
  - &admin age1mf7gjywm00gly7nr3glgj2xml4z4npvlwtqutu728elv6z4gafuqmdyp09
  - &host_tar_minyatur age1y6t2spugupljvtnml6j77c0hzhh5cf7h8pvw53c5exxcmz8fdu6ssh73c4
creation_rules:
  - key_groups:
    - age:
      - *admin
      - *host_tar_minyatur