keys:
  - &admin age1mf7gjywm00gly7nr3glgj2xml4z4npvlwtqutu728elv6z4gafuqmdyp09
  - &host_tar_elendil age1m7ures9waue54h4kz4mhaatc9mfhy25644wa5fsrhv4e7nwn3dwsmrnewh
  - &host_tar_meneldur age18dpvd349d4v5e76d3hv8345f7z4zd2ahhm3u8h25gfst95c9sucs0fadr6
creation_rules:
  - key_groups:
      - age:
          - *admin
          - *host_tar_elendil
          - *host_tar_meneldur
