# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/13d78a75-3020-4cd2-b967-1159f7418389";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7910-A014";
      fsType = "vfat";
    };

  fileSystems."/mnt/hdd" =
    { device = "/dev/disk/by-uuid/9fad5da3-bdf6-483d-b729-b301a2680726";
      fsType = "ext4";
    };

  fileSystems."/mnt/homelab" =
    { device = "192.168.0.11:/data";
      fsType = "nfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6f697509-ce82-4c5e-8351-c2cb72ea81ef"; }
    ];

}
